llvm-*: fix compatibility with legacy-support on 10.5
legacy-support since v1.0.5 contains `typedef char uuid_string_t[37]`
when removed patch contains `typedef char * uuid_string_t`.

An attempt to build it may fail with error:
```
../llvm/tools/dsymutil/SymbolMap.cpp:23:16: error: typedef redefinition with different types ('char *' vs 'char [37]')
typedef char * uuid_string_t;
               ^
/opt/local/include/LegacySupport/uuid/uuid.h:31:14: note: previous definition is here
typedef char uuid_string_t[37];
             ^
1 error generated.
```